### ISSUE TITLE
Contents of doc directory

### ISSUE THREAD

**Issue by BPaton** [michaelchughes/NPBayesHMM#1]
Thanks again for a very interesting toolbox. I am just getting started and am reading the quick start documentation and noticed that the document describing how a collection of sequential data is collected, specifically  "HOME/doc/DataGuide.pdf" but that files is not present in the repository?

Thanks.

**Comment by michaelchughes** [comment]
Sorry for the long delay! I had always intended on writing this documentation, but never got around to it until recently. See my recent updates to the repo, which include the new plain-text documentation: https://github.com/michaelchughes/NPBayesHMM/blob/master/doc/QuickStartGuide.md
